<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Πίνακας Ελέγχου',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 12:18:07',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Πολυμέσα',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 4,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:14:02',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Χρήστες',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 26,
                'order' => 1,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:12:53',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Ρόλοι',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => 26,
                'order' => 2,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-03 06:08:48',
                'route' => 'voyager.roles.index',
                'parameters' => 'null',
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Εργαλεία',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:14:04',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Διαχείριση μενού',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:13:25',
                'route' => 'voyager.menus.index',
                'parameters' => 'null',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Βάση Δεδομένων',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:13:25',
                'route' => 'voyager.database.index',
                'parameters' => 'null',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Πυξίδα',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:13:26',
                'route' => 'voyager.compass.index',
                'parameters' => 'null',
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:13:26',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Ρυθμίσεις',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-04-02 09:30:00',
                'updated_at' => '2019-04-02 13:13:25',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2019-04-02 09:30:01',
                'updated_at' => '2019-04-02 13:13:26',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 2,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-04-02 09:43:28',
                'updated_at' => '2019-04-02 09:43:28',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Περιεχόμενο',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-04-02 09:43:28',
                'updated_at' => '2019-04-02 13:14:01',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Άρθρα',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 1,
                'created_at' => '2019-04-02 09:43:28',
                'updated_at' => '2019-04-02 13:14:04',
                'route' => 'voyager.blog_posts.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Κατηγορίες',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 2,
                'created_at' => '2019-04-02 09:43:28',
                'updated_at' => '2019-04-02 13:14:05',
                'route' => 'voyager.categories.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Σελίδες',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 3,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 13:14:05',
                'route' => 'voyager.pages.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => 'Home',
                'url' => '/home',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'About',
                'url' => '/about',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => 'Contact',
                'url' => '/contact',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 3,
                'title' => 'Facebook',
                'url' => 'https://www.facebook.com/wearepvtl',
                'target' => '_blank',
                'icon_class' => 'fa-facebook-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'title' => 'Twitter',
                'url' => 'https://twitter.com/wearepvtl',
                'target' => '_blank',
                'icon_class' => 'fa-twitter-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'title' => 'Instagram',
                'url' => 'https://www.instagram.com/wearepvtl/',
                'target' => '_blank',
                'icon_class' => 'fa-instagram',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'title' => 'Google+',
                'url' => 'https://plus.google.com/100970850483584616344',
                'target' => '_blank',
                'icon_class' => 'fa-google-plus-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'LinkedIn',
                'url' => 'https://www.linkedin.com/company/pivotal-agency',
                'target' => '_blank',
                'icon_class' => 'fa-linkedin',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-04-02 09:43:30',
                'updated_at' => '2019-04-02 09:43:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Χρήστες & Δικαιώματα',
                'url' => '#',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-04-02 13:12:42',
                'updated_at' => '2019-04-02 13:15:50',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Redirects',
                'url' => '/admin/redirects',
                'target' => '_self',
                'icon_class' => 'voyager-external',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 8,
                'created_at' => '2019-04-03 05:46:12',
                'updated_at' => '2019-04-03 06:08:57',
                'route' => NULL,
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'WordPress Import',
                'url' => '/admin/wordpress-import',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 7,
                'created_at' => '2019-04-03 06:08:14',
                'updated_at' => '2019-04-03 06:26:19',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Themes',
                'url' => '/admin/themes',
                'target' => '_self',
                'icon_class' => 'voyager-paint-bucket',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 9,
                'created_at' => '2019-04-03 09:16:20',
                'updated_at' => '2019-04-03 09:20:07',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}